//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empid { get; set; }
        public string EmpName { get; set; }
        public int salary { get; set; }
        public int depid { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
